<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="runner.Local_Host" tests="1" time="48.322" ignored="7" failures="0" timestamp="27 Dec 2022 17:51:41 GMT" skipped="0" hostname="WorkPC" errors="1">
  <testcase name="HealthRec" time="48.322" classname="runner.Local_Host">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.openqa.selenium.remote.RemoteWebElement.isSelected(RemoteWebElement.java:149)
	at org.openqa.selenium.support.ui.Select.setSelected(Select.java:310)
	at org.openqa.selenium.support.ui.Select.selectByVisibleText(Select.java:116)
	at org.base.Base.dropDown(Base.java:251)
	at com.healthRec.Vitals.vitalsFeature(Vitals.java:26)
	at runner.Local_Host.HealthRec(Local_Host.java:692)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- HealthRec -->
  <testcase name="calendar" classname="runner.Local_Host">
    <skipped/>
  </testcase> <!-- calendar -->
  <testcase name="PatientModule" classname="runner.Local_Host">
    <skipped/>
  </testcase> <!-- PatientModule -->
  <testcase name="HomeModule" classname="runner.Local_Host">
    <skipped/>
  </testcase> <!-- HomeModule -->
  <testcase name="BillingModule" classname="runner.Local_Host">
    <skipped/>
  </testcase> <!-- BillingModule -->
  <testcase name="Message" classname="runner.Local_Host">
    <skipped/>
  </testcase> <!-- Message -->
  <testcase name="Settings" classname="runner.Local_Host">
    <skipped/>
  </testcase> <!-- Settings -->
  <testcase name="TeleDoctor" classname="runner.Local_Host">
    <skipped/>
  </testcase> <!-- TeleDoctor -->
</testsuite> <!-- runner.Local_Host -->
