<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-Q33L4MJO" ignored="7" name="Lite" tests="2" failures="2" timestamp="02 Mar 2023 09:15:00 GMT" time="0.024" errors="0">
  <testcase name="checkRecent3dCardUpdateInCardDetail" time="0.008" classname="org.LitePlan3d.EditCardDetails">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.LitePlan3d.EditCardDetails.checkRecent3dCardUpdateInCardDetail(EditCardDetails.java:291)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkRecent3dCardUpdateInCardDetail -->
  <testcase name="goToMarketPlaceAndGiveValidCvCAndCancel" time="0.001" classname="org.LitePlan3d.EditCardDetails">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at org.LitePlan3d.EditCardDetails.goToMarketPlaceAndGiveValidCvCAndCancel(EditCardDetails.java:316)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- goToMarketPlaceAndGiveValidCvCAndCancel -->
  <testcase name="verify3dcardInPayementPageAndEditCardDetails" time="0.0" classname="org.LitePlan3d.EditCardDetails">
    <ignored/>
  </testcase> <!-- verify3dcardInPayementPageAndEditCardDetails -->
  <testcase name="editCardLite" time="0.0" classname="org.LitePlan3d.EditCardDetails">
    <ignored/>
  </testcase> <!-- editCardLite -->
  <testcase name="verifySubscriptionWithoutCvc" time="0.0" classname="org.LitePlan3d.EditCardDetails">
    <ignored/>
  </testcase> <!-- verifySubscriptionWithoutCvc -->
  <testcase name="goToPayemntpageAddIncorrectCvc" time="0.0" classname="org.LitePlan3d.EditCardDetails">
    <ignored/>
  </testcase> <!-- goToPayemntpageAddIncorrectCvc -->
  <testcase name="editCardWithInvalidAndVerfiy" time="0.0" classname="org.LitePlan3d.EditCardDetails">
    <ignored/>
  </testcase> <!-- editCardWithInvalidAndVerfiy -->
  <testcase name="verify3dCardAndCompleteIt" time="0.0" classname="org.LitePlan3d.EditCardDetails">
    <ignored/>
  </testcase> <!-- verify3dCardAndCompleteIt -->
  <testcase name="giveValid3dCardCancelAndVerify" time="0.0" classname="org.LitePlan3d.EditCardDetails">
    <ignored/>
  </testcase> <!-- giveValid3dCardCancelAndVerify -->
</testsuite> <!-- Lite -->
